language: java
jdk:
   - openjdk11

before_install:
    - git submodule update --init --recursive

env:
  secure: "FEVnbx67LZNZEswG4BAs0pgHnLGifjFXYF3I2Ljt7HuW3JUzfzXJB6kl/pJy83Uig2QRrIeEKghsEJsa8D1TnwrWaWUH+PRTXqGnPe3FxWl6lCwh/oWVBLgj6pPAh/0LKpsw5hcw6ZZ590+3yHffvr3s8i1qKSbZGflf7UH3E07c1QHEM2qi8+rjSvuIjOt+ynSS44t6Jiewmc2iAY+J/eBbbLSkgevXo4tpUHhgsEtWqbCHmeKxoXMZX0ty8n+DmzVaZhrr6RCEkyfNIINvuwB2MldHuwCIsunZBTXPZViE8esSxiPPXwef7OwAsYaMzNCSdhmv7j3Gb1uMqCxqG4WpRfSzr+aeK9CcuPmdYXGODiN6MRcHwb/4/wf0F9Axg7vdAIB+fKUTkGDTV3/fwOLjuLcrss9v4uLot9p57t5HdmQ0zLDvIQCtCdlJgjpNssxb13peE8TD4JoD0opTCu9FQoC+gdwyTOkLK4aKTFFr8SNeiL6lx+0DsH8xaICm4BO1CMV/moRBOt6KChIgode7gUlDP2wm34/9EcapVoCaNSDPXHbYw0hPyHlBw59SAihomuEKGPPxX/bUABWzp5vJfSdKQlETNd1oiaEAGR2GnUl6RMYGVk7/uq2U+nAi7PYD0oXOHoMdr/yK7GGq/hR43bTeic514B+J1S5ronY="

script:
    - mvn install

after_success:
    - mvn -DrepoToken=$COVERALLS_TOKEN clean test jacoco:report coveralls:report

cache:
  directories:
    - '$HOME/.m2/repository'
