baseURL = "https://tamada.github.io/pochi"
languageCode = "en-US"
title = "Pochi"
enableEmoji = "true"
paginate = 10
hasCJKLanguage = "false"
theme = "cayman-hugo-theme"

[blackfriday]
    smartypants = false

[params]
    project_name = "pochi"
    project_tagline = "Detecting the software theft, the birthmark toolkit for the JVM platform."
    project_logo = "images/pochi.png"
    dateFormat = "Jan 02, 2006"
    footer = "[![GitHub](https://img.shields.io/badge/GitHub-tamada/pochi-blueviolet.svg?logo=github)](https://github.com/tamada/pochi) Made with [Hugo](https://gohugo.io/). Theme by [Cayman](https://github.com/zwbetz-gh/cayman-hugo-theme). Deployed to [GitHub Pages](https://pages.github.com/)."
    katex = true

[menu]
    [[menu.nav]]
        name = ":house: Home"
        url = "/"
        weight = 1
    [[menu.nav]]
        name = ":books: Birthmarks"
        url = "/birthmarks/"
        weight = 2
    [[menu.nav]]
        name = ":newspaper: What is pochi"
        url = "/description/"
        weight = 3
    [[menu.nav]]
        name = ":anchor: Install"
        url = "/install/"
        weight = 4
    [[menu.nav]]
        name = ":smile: About"
        url = "/about/"
        weight = 5
    [[menu.nav]]
        name = ":smile_cat: API docs"
        url = "/apidocs/"
        weight = 6
